version: 0.0
os: linux

files:
  - source:  /
    destination: /root/apache-tomcat-10.0.21/webapps/sample-tomcat
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: root
